project_name: crda
archives:
  - files:
      - LICENSE
      - docs/cli_README.md
    replacements:
      amd64: 64bit
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
release:
  draft: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - typo
      - (?i)foo
builds:
  - env: 
    - CGO_ENABLED=0 
    main: ./main.go
    ldflags: 
      - -s -w -X github.com/fabric8-analytics/cli-tools/pkg/version.version={{.Version}}
      - "-X 'github.com/fabric8-analytics/cli-tools/pkg/version.vendorInfo=Red Hat'"
      - -X github.com/fabric8-analytics/cli-tools/pkg/version.timestamp={{ .Timestamp }}
      - -X github.com/fabric8-analytics/cli-tools/pkg/version.commitHash={{ .ShortCommit }}
    id: crda
    binary: crda
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goarm: mips64
        gomips: hardfloat 
nfpms:
- id: crda
  vendor: CRDA
  maintainer: Deepak Sharma <deepshar@redhat.com>
  description: CLI Tools from team CRDA.
  homepage: https://github.com/fabric8-analytics/cli-tools
  license: MIT
  file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
      amd64: 64bit
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
  formats:
  - deb
  - rpm
