
name: CI-Acceptance-Tests 

on:
  push:
  pull_request:
    branches: [ main ]
    

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: actions/setup-python@v2
      with:
       python-version: '3.7'
   
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: build binary
      run: go build -o acceptance-tests/crda
    
    - name: Run Tests
      working-directory: ./acceptance-tests 
      env:
        THREE_SCALE_KEY: ${{ secrets.THREE_SCALE_KEY }}
        CRDA_KEY: ${{ secrets.CRDA_KEY }} 
      run: ./test.sh
      shell: bash