
name: CI-Acceptance-Tests 

on:
  push:
    # branches: [ main ]
  repository_dispatch:
    types: [acceptance-command]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: actions/setup-python@v2
      with:
       python-version: '3.7'
   
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Create comment
      if: github.event_name == 'repository_dispatch'  && github.event.action == 'acceptance-command'
      uses: peter-evans/create-or-update-comment@v1
      with:
        edit-mode: replace
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }} 
        body: |
            **Edit:** :test_tube: [CI has Started acceptance Test]( https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
        reactions: eyes  
    - name: build binary 
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: go build -o acceptance-tests/crda
    
    - name: build binary [Windows]
      if: runner.os == 'Windows'
      run: go build -o acceptance-tests/crda.exe
    
    - name: Install dependencies
      run: go mod vendor
    
    - name: Run Tests
      working-directory: ./acceptance-tests 
      env:
        THREE_SCALE_KEY: ${{ secrets.THREE_SCALE_KEY }}
        CRDA_KEY: ${{ secrets.CRDA_KEY }}
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: ./test.sh
      shell: bash
    
    - name: Upload log as artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test-log-${{ runner.os }}
        path: ./acceptance-tests/logs.txt
    - name: Create Success comment
      if: github.event_name == 'repository_dispatch'  && github.event.action == 'acceptance-command'
      uses: peter-evans/create-or-update-comment@v1
      with:
        edit-mode: replace
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body: |
          :v: [E2E Run Successfull](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
        reactions: hooray, heart
    - name: Create fail comment
      if: failure() && github.event_name == 'repository_dispatch'  && github.event.action == 'acceptance-command' 
      uses: peter-evans/create-or-update-comment@v1
      with:
        edit-mode: replace
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }} 
        body: |
          **Edit:** :facepalm: [Acceptance Tests Failed]( https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
        reactions: confused

      